---
- hosts: "this_ansible_server"
  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
      fingerprint: "7D:FE:DE:EE:C7:B9:D0:67:35:E4:C4:16:EC:7A:03:13:48:CD:CA:8D"
    register: login_response
  - name: "add host"    
    check_point_mgmt:
      command: add-host
      parameters:
        name: "host_demo_105"
        ip-address: "1.2.3.105" 
      session-data: "{{login_response}}"
  - name: "add new host new existing group"
    check_point_mgmt:
      command: set-group
      parameters:
        name: "group_demo"
        members:
          add:
          - "host_demo_105"
      session-data: "{{login_response}}"
  - name: "create new tcp service"
    check_point_mgmt:
      command: add-service-tcp
      parameters:
        name: "tcp_1005"
        port: "1005"
      session-data: "{{login_response}}"
  - name: "create rule at the top of a section called 'script rules'"
    check_point_mgmt:
      command: add-access-rule
      parameters:
        layer: "network"
        name: "created by ansible playbook"
        position:
          top: "script rules"
        source:
          - "group_demo"
        destination:
          - "host1"
          - "host2"
        service:
          - "tcp_1005"
        action: "accept"
      session-data: "{{login_response}}"
  - name: "publish"
    check_point_mgmt:
      command: publish
      session-data: "{{login_response}}"
  - name: "install policy"    
    check_point_mgmt:
      command: install-policy
      parameters:
        policy-package: "standard" 
      session-data: "{{login_response}}"

