---
- name: copy config template
  template:
    src: "{{ role_path }}/files/ftw_template"
    dest: /home/admin/ftw_template

- name: run first time wizard
  #the config_system command will terminate the connection after processing.
  #this causes the play to terminate prematurely
  #as a work around the sshpass command is used to run config_system
  local_action: command sshpass -p "{{ansible_ssh_pass|default('')}}" ssh admin@{{inventory_hostname}} /bin/config_system -f /home/admin/ftw_template
  ignore_errors: true


- name: reboot
  command: shutdown -r now
  async: 0
  poll: 0
  ignore_errors: True

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
